### ISSUE TITLE
CameraActivity has leaked - After the image is captured

### ISSUE THREAD

**Issue by riinav** [boxme/SquareCamera#2]
Thank you for a wonderful abstraction of Camera API. The Code is clean and I really like the minimal amount of code required to get this lib working.

However I am getting this error sometimes. It happens after the image is captured and ticking on the right icon (in fragment_edit_save_photo.xml), would look into this and let us know the cause.

Also If you could add this lib to gradle repo would be great.

```java
E/ActivityThread﹕ Activity com.desmond.squarecamera.CameraActivity has leaked ServiceConnection android.media.MediaScannerConnection@425737d0 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.desmond.squarecamera.CameraActivity has leaked ServiceConnection android.media.MediaScannerConnection@425737d0 that was originally bound here
            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:977)
            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:871)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1625)
            at android.app.ContextImpl.bindService(ContextImpl.java:1608)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
            at android.media.MediaScannerConnection.connect(MediaScannerConnection.java:119)
            at android.media.MediaScannerConnection.scanFile(MediaScannerConnection.java:238)
            at com.desmond.squarecamera.ImageUtility.savePicture(ImageUtility.java:96)
            at com.desmond.squarecamera.EditSavePhotoFragment.savePicture(EditSavePhotoFragment.java:103)
            at com.desmond.squarecamera.EditSavePhotoFragment.access$000(EditSavePhotoFragment.java:21)
            at com.desmond.squarecamera.EditSavePhotoFragment$1.onClick(EditSavePhotoFragment.java:73)
            at android.view.View.performClick(View.java:4445)
            at android.view.View$PerformClick.run(View.java:18446)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
````

**Comment by boxme** [comment]
Fixed in commit eef6cf
