### ISSUE TITLE
setParameters failed

### ISSUE THREAD

**Issue by philipgiuliani** [boxme/SquareCamera#34]
Some devices are experiencing the following error. Do you have any idea what this could be?

60%: ASUS T00I
40%: ASUS T00J
5%: Samsung A700F
3%: Lenovo Lifetab P981X

I know that the ASUS devices has no flash. But before setting the flashmode its checked...

Unusable stacktrace from Crashlytics:
```
Fatal Exception: java.lang.RuntimeException: setParameters failed
       at android.hardware.Camera.native_setParameters(Camera.java)
       at android.hardware.Camera.setParameters(Camera.java:1707)
       at com.keepinmind.lifeshot.ui.CameraFragment.setupCamera(Unknown Source)
       at com.keepinmind.lifeshot.ui.CameraFragment.getCamera(Unknown Source)
       at com.keepinmind.lifeshot.ui.CameraFragment.surfaceCreated(Unknown Source)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:580)
       at android.view.SurfaceView.access$000(SurfaceView.java:90)
       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:183)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1917)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1043)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by bendikhk** [comment]
Did you find any solution to this problem? Receiving the same problem for Huawei phones.

**Comment by philipgiuliani** [comment]
No sorry :( I still get crash reports because of this...
