### ISSUE TITLE
app passed NULL surface

### ISSUE THREAD

**Issue by syaheer** [boxme/SquareCamera#40]
Hi

Thanks for this great library. Its been working fine on my device but there is something on the log that is bugging me. It says:

> 03-02 20:18:30.962 18221-18221/com.desmond.demo D/Camera: app passed NULL surface
> 03-02 20:18:31.051 18221-18221/com.desmond.demo W/CameraBase: An error occurred while connecting to camera: 0
> 03-02 20:18:31.051 18221-18221/com.desmond.demo D/CameraFragment: Can't open camera with id 0
> 03-02 20:18:31.051 18221-18221/com.desmond.demo W/System.err: java.lang.RuntimeException: Fail to connect to camera service
> 03-02 20:18:31.052 18221-18221/com.desmond.demo W/System.err:     at android.hardware.Camera.<init>(Camera.java:497)
> 03-02 20:18:31.052 18221-18221/com.desmond.demo W/System.err:     at android.hardware.Camera.open(Camera.java:342)
> 03-02 20:18:31.052 18221-18221/com.desmond.demo W/System.err:     at com.desmond.squarecamera.CameraFragment.getCamera(CameraFragment.java:215)
> 03-02 20:18:31.052 18221-18221/com.desmond.demo W/System.err:     at com.desmond.squarecamera.CameraFragment.surfaceCreated(CameraFragment.java:458)
> 03-02 20:18:31.052 18221-18221/com.desmond.demo W/System.err:     at android.view.SurfaceView.updateWindow(SurfaceView.java:580)
> 03-02 20:18:31.052 18221-18221/com.desmond.demo W/System.err:     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
> 03-02 20:18:31.052 18221-18221/com.desmond.demo W/System.err:     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
> 03-02 20:18:31.052 18221-18221/com.desmond.demo W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1970)
> 03-02 20:18:31.052 18221-18221/com.desmond.demo W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:550)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at android.os.Looper.loop(Looper.java:135)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
> 03-02 20:18:31.053 18221-18221/com.desmond.demo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
> 03-02 20:34:50.202 18221-18231/com.desmond.demo I/art: Debugger is no longer active

**Comment by philipgiuliani** [comment]
Hi have you tried to open it on an Device without camera? (simulator)? Have you added the permissions?

**Comment by syaheer** [comment]
I am using a Nexus 7. Yes I have added the permissions.
