### ISSUE TITLE
Problem with adding camera.

### ISSUE THREAD

**Issue by fadelakin** [boxme/SquareCamera#6]
Hi there,

I'm a total noob but it seems I have a problem with adding this module. When I run my app, it says that CameraActivity is not declared in my manifest and throws an error. Any help?

EDIT: I figured out how to include but now I get this error:
```

05-05 21:06:08.225  25802-25802/com.joinspur.spur E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.joinspur.spur, PID: 25802
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.setDisplayOrientation(int)' on a null object reference
            at com.desmond.squarecamera.CameraFragment.determineDisplayOrientation(CameraFragment.java:250)
            at com.desmond.squarecamera.CameraFragment.startCameraPreview(CameraFragment.java:184)
            at com.desmond.squarecamera.CameraFragment.surfaceCreated(CameraFragment.java:372)
            at android.view.SurfaceView.updateWindow(SurfaceView.java:580)
            at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
            at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1970)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by fadelakin** [comment]
Actually nevermind. I figured it out. I added the camera permissions and it worked. I'm not very smart.

**Comment by IlyaEremin** [comment]
@fadelakin hahaha, very funny comment :+1: I'm also faced with this issue

**Comment by simonberglund** [comment]
@fadelakin  it shouldn't say that you should declare it in the manifest though. Im also dump in that case =)
